import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import { Container, Theme } from "@radix-ui/themes";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Theme
          appearance="dark"
          accentColor="yellow"
          grayColor="sage"
          panelBackground="translucent"
        >
          <div
            className="fixed -z-50 h-[75vh] w-screen lg:h-screen "
            style={{
              backgroundImage: 'url("/background.svg")',
              backgroundSize: "cover",
              backgroundRepeat: "no-repeat",
            }}
          ></div>
          <Container
            minWidth={{ md: "1000px", lg: "1200px" }}
            maxWidth={{ md: "1000px", lg: "1200px" }}
          >
            <Header />
            {children}
          </Container>
          <Footer />
        </Theme>
      </body>
    </html>
  );
}
